import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componants/share/Navbar";
import Footer from "@/componants/share/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="">
          <Navbar></Navbar>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="">
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
